name 'ohai_ms_licensing'
maintainer 'James Massardo'
maintainer_email 'james@dxrf.com'
license 'Apache-2.0'
description 'Ohai plugin for collecting MS Windows Licensing information'
version '1.0.0'
chef_version '>= 12.14'
depends 'ohai'
supports 'windows'
issues_url 'https://github.com/jmassardo/ohai_ms_licensing/issues'
source_url 'https://github.com/jmassard/ohai_ms_licensing'
